### ISSUE TITLE
Migrate to Github Actions due to Travis memory limits

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#1864]
**Problem**
Tests are frequently failing on Travis due to out-of-memory errors. Example log:

```text
 form_feedback.server.model › Schema › should create and save successfully
    spawn ENOMEM
      at Object.spawn [as default] (node_modules/mongodb-memory-server-core/node_modules/cross-spawn/index.js:12:24)
      at MongoInstance.Object.<anonymous>.MongoInstance._launchMongod (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:228:36)
      at MongoInstance.<anonymous> (node_modules/mongodb-memory-server-core/src/util/MongoInstance.ts:140:30)
      at step (node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:44:23)
      at Object.next (node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:25:53)
      at fulfilled (node_modules/mongodb-memory-server-core/lib/util/MongoInstance.js:16:58)
```

**Attempted fixes**
1. [Using nproc to limit number of workers spawned](https://github.com/opengovsg/FormSG/pull/1860)
2. [Using --runInBand option to limit process spawn](https://github.com/opengovsg/FormSG/pull/1863)

**Solution**
Migrate to GitHub Actions, since the same tests appear to pass immediately.

**Comment by liangyuanruo** [comment]
Closing as #1870 addressed the immediate issue
