### ISSUE TITLE
Investigate what is hampering Mongoose library upgrades

### ISSUE THREAD

**Issue by liangyuanruo** [opengovsg/FormSG#506]
Server fails to start if mongoose is upgraded:

```text
[2] (node:51992) UnhandledPromiseRejectionWarning: Error: Connection strategy not found
[2]     at new MongoStore (FormSG/node_modules/connect-mongo/src/index.js:127:15)
[2]     at Object.sessionMiddlewares [as default] (FormSG/dist/backend/loaders/express/session.js:20:16)
[2]     at FormSG/dist/backend/loaders/express/index.js:103:30
```

Related: https://github.com/opengovsg/FormSG/pull/394, https://github.com/opengovsg/FormSG/pull/504

**Comment by karrui** [comment]
It's a bug introduced in 5.10.0, see https://github.com/Automattic/mongoose/issues/9496.

This has been fixed in 5.10.10 via https://github.com/Automattic/mongoose/pull/9497, I'm opening a new PR to fix it since dependabot won't trigger due to the pinning.
