### ISSUE TITLE
Failed builds due to Localstack installation

### ISSUE THREAD

**Issue by mantariksh** [opengovsg/FormSG#66]
Builds are failing intermittently due to the following error, both in the old repo and this one. They usually work after being re-triggered, but this should be fixed ASAP.

```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-je0z2fvi/amazon-kclpy-ext/setup.py", line 285, in <module>
        zip_safe=False,
      File "/opt/python/3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/opt/python/3.7.1/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-je0z2fvi/amazon-kclpy-ext/setup.py", line 228, in run
        downloader.download_and_check()
      File "/tmp/pip-install-je0z2fvi/amazon-kclpy-ext/setup.py", line 130, in download_and_check
        raise RuntimeError(self.warning_string(missing_jars))
    RuntimeError: The following jars were not installed because they were not
    present in this package at the time of installation:
      amazon_kclpy/jars/commons-lang3-3.7.jar
    This doesn't affect the rest of the installation, but may make it more
    difficult for you to run the sample app and get started.
    
    You should consider running:
    
        python setup.py download_jars
        python setup.py install
    
    Which will download the required jars and rerun the install.
    
    
    ----------------------------------------
Command "/opt/python/3.7.1/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-je0z2fvi/amazon-kclpy-ext/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-o9cl1vd0/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-je0z2fvi/amazon-kclpy-ext/
You are using pip version 10.0.1, however version 20.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command "pip3 install --user localstack[full]" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by mantariksh** [comment]
This seems to have resolved itself, will monitor for a few more days

**Comment by mantariksh** [comment]
@arshadali172 @karrui @shuli-ogp do any of you want to help pick this up? I haven't had any luck :( the branch is `fix-kclpy-error`.

**Comment by liangyuanruo** [comment]
@mantariksh can this be closed?

**Comment by mantariksh** [comment]
@liangyuanruo Yes, I haven't seen this error in a long time so perhaps the fix has been made upstream
